# Starter pipeline



trigger:
- master

pool:

  vmImage: "vs2017-win2016"

steps:
- task: UiPathInstallPlatform-preview@2


- task: UiPathPack@2
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)\MyLibrary\project.json'
    orchestratorConnection: 'UiBank_Orchestrator'
    outputType: 'Library'
    outputPath: 


- task: UiPathDeploy@2
  inputs:
    orchestratorConnection: 'UiBank_Orchestrator'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'ThomasStocker'
    environments: 'ThomasStockerEnvironment'

    

- task: UiPathTest@2
  inputs:
    testTarget: 'TestProject'
    orchestratorConnection: 'Orchestrator'
    testProjectPath: '$(Build.ArtifactStagingDirectory)\Output'
    environment: 'ThomasStockerEnvironment'
    folderName: 'Default'