# Starter pipeline



trigger:
- master

pool:

  vmImage: "vs2017-win2016"

steps:
- task: UiPathInstallPlatform-preview@2



    

- task: UiPathTest@2
  inputs:
    testTarget: 'TestProject'
    orchestratorConnection: 'Orchestrator'
    testProjectPath: '$(Build.ArtifactStagingDirectory)\Output'
    environment: 'ThomasStockerEnvironment'
    folderName: 