# Starter pipeline



trigger:
- master

pool:

  vmImage: "vs2017-win2016"

steps:
- task: UiPathInstallPlatform-preview@2



    

- task: UiPathTest@2
  inputs:
    testTarget: 'TestSet'
    orchestratorConnection: 'Orchestrator'
    testSet: 'Compasso Webinar'
    folderName: 'ThomasStocker'
    testReportDestination: 'output.xml'