# Starter pipeline



trigger:
- master

pool:

  vmImage: "vs2017-win2016"

steps:



- task: UiPathPack@2
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)\RPATesting_Community_Webinar\project.json'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml